import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About Makazo
        </h1>


        <div className={styles.grid}>
            <div className={styles.card}>
                <p>This is the card for the new info for this page which will be extended today</p>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by Makazo 2021-2022
      </footer>
    </div>
  )
}

export default About
